name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: BioDrop

      - name: Run tests
        run: npm run test
        working-directory: BioDrop

      - name: Run test coverage
        run: npm run test:coverage
        working-directory: BioDrop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/final_project/BioDrop:latest -t ${{ secrets.DOCKER_USERNAME }}/bulletin-board-app:${{ github.sha }} .
        working-directory: BioDrop

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/final_project/BioDrop:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/final_project/BioDrop:${{ github.sha }}
